id: P177A0D9A
initial_creation_type: input
source_metadata:
  title: Words of the Buddha
  language: es
  description: 'A selection of works by the Buddha himself, many of which feature
    in the Kangyur (bka'' ''gyur), the Tibetan canonical collection of the Buddha''s
    Word:'
  volume:
    e36d685d67644a92839264f156aafaec:
      title: The Auspicious Verses of the Seven Successive Buddhas
      parent: Auspiciousness
    47f6dcd6f743474a99b00a6119856ece:
      title: The Dhāraṇī of Amitāyus
      parent: Dhāraṇī
    df22764f038e4a909b69fa54720d4d46:
      title: The Dhāraṇī of Glorious Vajraṇakhī
      parent: Dhāraṇī
    6539ee15c917459fada97533532029ef:
      title: The Dhāraṇī of Stream of Wealth (Vasudhārā)
      parent: Dhāraṇī
    48de94ace391481f894a184da1449839:
      title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from
        the Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
      parent: Dhāraṇī
    b6c2c0fa3ff145b889fe14babfbc838a:
      title: The Noble Essence of Dependent Origination
      parent: Dhāraṇī
    eb7f8c090d234173ba5c5d24c2fe88d0:
      title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
      parent: Dhāraṇī
    17d36acfe8b146bfba19da86dae7be07:
      title: The Noble Mārīcī Dhāraṇī
      parent: Dhāraṇī
    355f8201f8e847e480a9a0aa96cbea2a:
      title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
      parent: Dhāraṇī
    e056adf70e3148bdbfbf1d98163fa3ce:
      title: Prayer for the Future of the Dharma
      parent: Prayers
    abb34e1f91004cd59f7daacefcbb15ab:
      title: 'The Clarifying Light: A Prophecy of the Future'
      parent: Prophecy
    980d2568ec494110b00dcdad5c7a5be0:
      title: The Song of the Vajra
      parent: Songs
    02aa847242f9446abbb64fdf14bdfbf8:
      title: Maitreya's Aspiration
      parent: Sūtra
    4666dfd0ce3e44ee9b97141bec3415f7:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Sūtra
    71db4e6970914e4d8f00df07f06092dd:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Sūtra
    699ab5d06ba84bf2bed1e17e436b0af0:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Sūtra
    caf4f63612c64c45bd2abf8e14bf4a97:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Sūtra
    d94fa34b5e3e412692f921f7a2ac285f:
      title: The Noble Sūtra Teaching the Eleven Perceptions
      parent: Sūtra
    3af912a4be2146dda4e275e3080d2c2d:
      title: The Noble Sūtra of Recalling the Three Jewels
      parent: Sūtra
    8ae281e67cc349aca3639cdf7fa17074:
      title: The Noble Sūtra of the Teaching on the Four Factors
      parent: Sūtra
    6582bb4aef03409f8eccda2a100ceb69:
      title: The Perfection of Wisdom, Mother of All Tathāgatas, ‘In One Syllable’
      parent: Sūtra
    ba36a8094dad48dbb972e0aa8d4e76e9:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtra
    7d4b1b4f4197443c9aa77f4c17788e84:
      title: A Section of the Vajrakīla Root Tantra
      parent: Tantra
    5d0212f8f82b46f3940eb1ed8935d64e:
      title: Daily Confession (from the Vajrapañjara Tantra)
      parent: Tantra
    eb0c88ca682c43fd954060731e8e840a:
      title: The Lament of Rudra
      parent: Tantra
    8685caefc606491382618c99e1e4d717:
      title: The Praise to Tārā with Twenty-One Verses of Homage and The Excellent
        Benefits of Reciting the Praise
      parent: Tantra
    46d357deac804fbd9b593662b0c73ef7:
      title: The Twenty-Eight Commitments
      parent: Tantra
    737c4846485b4367b0eefeea527d0db0:
      title: The Ultimate Inexpressible Confession (Yeshe Kuchokma)
      parent: Tantra
    ff208af0d9cd4945a10437dab8fc664d:
      title: Verses of Confession 'Düsum Deshekma'
      parent: Tantra
created_at: '2022-03-01T02:07:32.761065'
last_modified_at: '2022-03-01T02:07:32.761068'
